In [3]:
import numpy as np
from numpy.linalg import inv
X = [4,7,10,2,3,9]
X = np.array([[1, x] for x in X])
y = [-1,-1,-1,1,1,1]
y = np.array(y)
w = inv(X.T@X)@X.T@y

In [5]:
y_pred = X@w
y_pred = np.sign(y_pred)

In [6]:
y_pred

array([ 1., -1., -1.,  1.,  1., -1.])

In [7]:
X_test = np.array([1,6])
y_pred = X_test@w
y_pred = np.sign(y_pred)
y_pred

-1.0

In [10]:
X = [4,7,10,2,3,9]
X = np.array([[x] for x in X])

from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(4)
P = poly.fit_transform(X)
w = inv(P.T@P)@P.T@y
y_pred = np.sign(P@w)       

In [11]:
y_pred

array([-1., -1., -1.,  1.,  1.,  1.])

In [12]:
y_pred = np.sign(poly.fit_transform([[6]])@w)

In [13]:
y_pred

array([-1.])

In [14]:
import pandas as pd
df = pd.DataFrame(
    {
        'X': [3.3459,1.0893,3.2103,1.744,1.6762],
        'Y': [2.7435,2.9113,1.4706,1.2895,2.1366],
        'Z': [-1.7253,-.7804,-.9944,.5307,-1.0502],
        'y': [2.9972,1.1399,2.228,.3387,2.5042]
    }
)
df

X       Y       Z       y
0  3.3459  2.7435 -1.7253  2.9972
1  1.0893  2.9113 -0.7804  1.1399
2  3.2103  1.4706 -0.9944  2.2280
3  1.7440  1.2895  0.5307  0.3387
4  1.6762  2.1366 -1.0502  2.5042

In [15]:
df.corr()

X         Y         Z         y
X  1.000000 -0.153327 -0.527787  0.650990
Y -0.153327  1.000000 -0.641418  0.372218
Z -0.527787 -0.641418  1.000000 -0.930813
y  0.650990  0.372218 -0.930813  1.000000

In [16]:
from sklearn.metrics import mean_squared_error

X = [0.2,0.7,1.8,2.2,3.7,4.1,4.5,5.1,6.3,7.4]
y = [2.1,1.5,5.8,6.1,9.1,9.5,9.8,12.7,13.8,15.9]
avg_y = [sum(y)/len(y) for i in y]
print(mean_squared_error(y,avg_y))


20.6381


In [17]:
#split at x = 3 -> find MSE at depth 1
y1 =  [2.1,1.5,5.8,6.1]
y2 = [9.1,9.5,9.8,12.7,13.8,15.9]
avg_y1 = [sum(y1)/len(y1) for i in y1]
avg_y2 = [sum(y2)/len(y2) for i in y2]
print(mean_squared_error(y1,avg_y1) + mean_squared_error(y2,avg_y2))


10.728541666666667
